.catalog:
  name: "Percona XtraDB Cluster"
  version: 5.6.28-rancher1
  description: |
    Percona XtraDB Cluster 5.6.28
  questions:
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
      default: "password"
    - variable: "pxc_sst_password"
      type: string
      required: true
      label: "PXC SST Password"
      description: "Password given to the sst mysql user"   
      default: "password"   
    - variable: "mysql_database"
      type: string
      required: false
      label: "MySQL Database Name"
      description: "MySQL database to create"
    - variable: "mysql_user"
      type: string
      required: false
      description: "MySQL user for the created database"
      label: "MySQL DB User"
    - variable: "mysql_password"
      type: string
      required: false
      label: "MySQL DB Password"
      description: "Password for the MySQL user of the created database"
    - variable: "innodb_buffer_pool_size"
      type: string
      required: true
      label: "innodb_buffer_pool_size"
      description: "innodb_buffer_pool_size"
      default: "6144M"
    - variable: "innodb_log_file_size"
      type: string
      required: true
      label: "innodb_log_file_size"
      description: "innodb_log_file_size"
      default: "2048M"
    - variable: "innodb_log_buffer_size"
      type: string
      required: true
      label: "innodb_log_buffer_size"
      description: "innodb_log_buffer_size"
      default: "256M"
    - variable: "max_connections"
      type: string
      required: true
      label: "max_connections"
      description: "max_connections"
      default: "2000"
    - variable: "innodb_flush_log_at_trx_commit"
      type: string
      required: true
      label: "innodb_flush_log_at_trx_commit"
      description: "If the value of innodb_flush_log_at_trx_commit is 0, the log buffer is written out to the log file once per second and the flush to disk operation is performed on the log file, but nothing is done at a transaction commit. When the value is 1, the log buffer is written out to the log file at each transaction commit and the flush to disk operation is performed on the log file. When the value is 2, the log buffer is written out to the file at each commit, but the flush to disk operation is not performed on it. However, the flushing on the log file takes place once per second also when the value is 2. Note that the once-per-second flushing is not 100% guaranteed to happen every second, due to process scheduling issues."
      default: "1"
pxc:
  scale: 3
  health_check:
    port: 8000
    interval: 2000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000  
  metadata:
    mysqld: |
      innodb_buffer_pool_size=${innodb_buffer_pool_size}
      innodb_doublewrite=0
      innodb_flush_log_at_trx_commit=${innodb_flush_log_at_trx_commit}
      innodb_file_per_table=1
      innodb_log_file_size=${innodb_log_file_size}
      innodb_log_buffer_size=${innodb_log_buffer_size}
      innodb_support_xa=0
      query_cache_size=0
      query_cache_type=0
      sync_binlog=0
      max_connections=${max_connections}
      default-time-zone='+8:00'
      character-set-server=utf8
      lower_case_table_names=1
      wsrep_sst_auth=sstuser:${pxc_sst_password}